#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# All compiler and module caches stay in this workspace rather than home directories.
WORKSPACE_DIR="$PROJECT_DIR"
# The supplied layout keeps deliverables under outputs/. A standalone checkout
# keeps its build work inside the project instead of walking into the user's home.
if [ "$(basename "$(dirname "$PROJECT_DIR")")" = "outputs" ]; then
    WORKSPACE_DIR="$(cd "$PROJECT_DIR/../.." && pwd)"
fi
BUILD_ROOT="${IDEADOCK_BUILD_ROOT:-$WORKSPACE_DIR/work/IdeaDock-build}"
APP_DESTINATION="${1:-$PROJECT_DIR/../IdeaDock.app}"
case "$APP_DESTINATION" in
    *.app) ;;
    *) echo "Output must end in .app: $APP_DESTINATION" >&2; exit 1 ;;
esac
mkdir -p "$BUILD_ROOT/clang-modules" "$BUILD_ROOT/swift-modules" "$BUILD_ROOT/swiftpm-cache" "$BUILD_ROOT/swiftpm-config" "$BUILD_ROOT/swiftpm-security"
export CLANG_MODULE_CACHE_PATH="$BUILD_ROOT/clang-modules"
export SWIFTPM_MODULECACHE_OVERRIDE="$BUILD_ROOT/swift-modules"

COMMON_ARGS=(--package-path "$PROJECT_DIR" --scratch-path "$BUILD_ROOT/package" --cache-path "$BUILD_ROOT/swiftpm-cache" --config-path "$BUILD_ROOT/swiftpm-config" --security-path "$BUILD_ROOT/swiftpm-security" --manifest-cache local --disable-sandbox)
# A distributable local app does not need debug symbols; avoiding dSYM generation
# also keeps the build compatible with restricted command-line environments.
swift build "${COMMON_ARGS[@]}" -c release -debug-info-format none
BIN_DIR="$(swift build "${COMMON_ARGS[@]}" -c release -debug-info-format none --show-bin-path)"
STAGING_APP="$BUILD_ROOT/IdeaDock-staging-$$.app"
trap 'rm -rf "$STAGING_APP"' EXIT
rm -rf "$STAGING_APP"
mkdir -p "$STAGING_APP/Contents/MacOS" "$STAGING_APP/Contents/Resources"
cp "$BIN_DIR/IdeaDock" "$STAGING_APP/Contents/MacOS/IdeaDock"
cp "$PROJECT_DIR/Resources/Info.plist" "$STAGING_APP/Contents/Info.plist"
for BUNDLE in "$BIN_DIR"/*.bundle; do
    if [ -d "$BUNDLE" ]; then
        cp -R "$BUNDLE" "$STAGING_APP/Contents/Resources/"
        # SwiftPM's generated Bundle.module lookup checks beside the executable.
        cp -R "$BUNDLE" "$STAGING_APP/Contents/MacOS/"
    fi
done
if [ -f "$PROJECT_DIR/Resources/IdeaDock.icns" ]; then
    cp "$PROJECT_DIR/Resources/IdeaDock.icns" "$STAGING_APP/Contents/Resources/IdeaDock.icns"
fi
/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$STAGING_APP/Contents/Info.plist" >/dev/null
/usr/bin/codesign --force --deep --sign - "$STAGING_APP"
/usr/bin/codesign --verify --deep --strict "$STAGING_APP"
mkdir -p "$(dirname "$APP_DESTINATION")"
if [ -e "$APP_DESTINATION" ]; then
    # Replace only an existing bundle generated by this project.
    if [ ! -f "$APP_DESTINATION/Contents/Info.plist" ] || [ "$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP_DESTINATION/Contents/Info.plist" 2>/dev/null)" != "app.local.IdeaDock" ]; then
        echo "Refusing to replace an unrelated existing app: $APP_DESTINATION" >&2
        exit 1
    fi
    rm -rf "$APP_DESTINATION"
fi
cp -R "$STAGING_APP" "$APP_DESTINATION"
/usr/bin/codesign --verify --deep --strict "$APP_DESTINATION"
echo "Built: $APP_DESTINATION"
